AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Elastic Serverless Forwarder

  Send observability data from your AWS environment to Elastic.

Parameters:
  ElasticServerlessForwarderS3ConfigFile:
    Type: String
    Default: "s3://"
    Description: S3 URL of the config yaml file (to be set as `S3_CONFIG_FILE` env variable)
  ElasticServerlessForwarderSSMSecrets:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of AWS SSM Secrets ARNs referenced in the config yaml file
  ElasticServerlessForwarderKMSKeys:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of AWS KMS Keys ARNs to be used for decrypting AWS SSM Secrets referenced in the config yaml file
  ElasticServerlessForwarderSQSEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Direct SQS queues ARNs to set as event triggers for the Lambda
  ElasticServerlessForwarderS3SQSEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of S3 SQS Event Notifications ARNs to set as event triggers for the Lambda
  ElasticServerlessForwarderKinesisEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Kinesis Data Stream ARNs to set as event triggers for the Lambda
  ElasticServerlessForwarderCloudWatchLogsEvents:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of Cloudwatch Logs Log Groups ARNs to set subscription filters on the Lambda for
  ElasticServerlessForwarderS3Buckets:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of S3 buckets ARNs that are the sources of the S3 SQS Event Notifications
  ElasticServerlessForwarderVPCSecurityGroupIds:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of security groups IDs in the VPC that includes the ElasticSearch host(s)
  ElasticServerlessForwarderVPCSubnetIds:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma delimited list of subnet IDs in the VPC that includes the ElasticSearch host(s)
  ElasticServerlessForwarderReservedConcurrentExecutions:
    Type: Number
    Default: 0
    Description: The AWS Lambda ReservedConcurrentExecutions property
Conditions:
  HasVPC:
    Fn::And:
      - !Not [ !Equals [ !Join [",", !Ref ElasticServerlessForwarderVPCSecurityGroupIds], "" ] ]
      - !Not [ !Equals [ !Join [",", !Ref ElasticServerlessForwarderVPCSubnetIds], "" ] ]

Resources:
  ElasticServerlessForwarderEventMacro:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:%awsRegion%:%accountID%:applications/helper-macro-%sarAppName%
        SemanticVersion: %semanticVersion%
  ElasticServerlessForwarderApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:%awsRegion%:%accountID%:applications/helper-application-%sarAppName%
        SemanticVersion: %semanticVersion%
      Parameters:
        ElasticServerlessForwarderS3ConfigFile: !Ref ElasticServerlessForwarderS3ConfigFile
        ElasticServerlessForwarderSSMSecrets: !Join [",", !Ref ElasticServerlessForwarderSSMSecrets]
        ElasticServerlessForwarderKMSKeys: !Join [",", !Ref ElasticServerlessForwarderKMSKeys]
        ElasticServerlessForwarderSQSEvents: !Join [",", !Ref ElasticServerlessForwarderSQSEvents]
        ElasticServerlessForwarderS3SQSEvents: !Join [",", !Ref ElasticServerlessForwarderS3SQSEvents]
        ElasticServerlessForwarderKinesisEvents: !Join [",", !Ref ElasticServerlessForwarderKinesisEvents]
        ElasticServerlessForwarderCloudWatchLogsEvents: !Join [",", !Ref ElasticServerlessForwarderCloudWatchLogsEvents]
        ElasticServerlessForwarderS3Buckets: !Join [",", !Ref ElasticServerlessForwarderS3Buckets]
        ElasticServerlessForwarderVPCSecurityGroupIds: !Join [",", !Ref ElasticServerlessForwarderVPCSecurityGroupIds]
        ElasticServerlessForwarderVPCSubnetIds: !Join [",", !Ref ElasticServerlessForwarderVPCSubnetIds]
        ElasticServerlessForwarderReservedConcurrentExecutions: !Ref ElasticServerlessForwarderReservedConcurrentExecutions
    DependsOn: ElasticServerlessForwarderEventMacro
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Elastic Serverless Forwarder Configuration options
        Parameters:
          - ElasticServerlessForwarderS3ConfigFile
          - ElasticServerlessForwarderSSMSecrets
          - ElasticServerlessForwarderKMSKeys
      - Label:
          default: Elastic Serverless Forwarder Events options
        Parameters:
          - ElasticServerlessForwarderSQSEvents
          - ElasticServerlessForwarderS3SQSEvents
          - ElasticServerlessForwarderKinesisEvents
          - ElasticServerlessForwarderCloudWatchLogsEvents
      - Label:
          default: Elastic Serverless Forwarder S3 Buckets Permissions options
        Parameters:
          - ElasticServerlessForwarderS3Buckets
      - Label:
          default: Elastic Serverless Forwarder Events options
        Parameters:
          - ElasticServerlessForwarderVPCSecurityGroupIds
          - ElasticServerlessForwarderVPCSubnetIds
    ParameterLabels:
      ElasticServerlessForwarderS3ConfigFile:
        default: Config File
      ElasticServerlessForwarderSSMSecrets:
        default: AWS SSM Secrets
      ElasticServerlessForwarderKMSKeys:
        default: AWS KMS Keys
      ElasticServerlessForwarderCloudWatchLogsEvents:
        default: Cloudwatch Logs subscription filters
      ElasticServerlessForwarderKinesisEvents:
        default: Kinesis Data Stream event triggers
      ElasticServerlessForwarderS3SQSEvents:
        default: S3 SQS Event Notifications event triggers
      ElasticServerlessForwarderSQSEvents:
        default: Direct SQS queues event triggers
      ElasticServerlessForwarderS3Buckets:
        default: S3 buckets of S3 SQS Event Notifications
      ElasticServerlessForwarderVPCSecurityGroupIds:
        default: VPC Security Group IDs for the lambda
      ElasticServerlessForwarderVPCSubnetIds:
        default: VPC Subnet IDs for the lambda
      ElasticServerlessForwarderReservedConcurrentExecutions:
        default: ReservedConcurrentExecutions property for the lambda
  AWS::ServerlessRepo::Application:
    Name: %sarAppName%
    Description: Send observability data from your AWS environment to Elastic.
    Author: %sarAuthorName%
    Labels: ['s3', 'logs', 'analytics', 'observability', 'monitoring', 'Elastic']
    SemanticVersion: %semanticVersion%
    LicenseUrl: %codeUri%/LICENSE.txt
    ReadmeUrl: %codeUri%/README.md
    HomePageUrl: https://github.com/elastic/elastic-serverless-forwarder
    SourceCodeUrl: https://github.com/elastic/elastic-serverless-forwarder
